/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/mir/inicio/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description El período, y cómo viene la presentación de la jurisdicción. */
        get: operations["mir_inicio_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mir/sesion/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Quién está conectado y qué puede hacer: lo primero que pide el front. */
        get: operations["mir_sesion_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ArchivoDelPeriodo: {
            codigo: string;
            nombre: string;
            obligatorio: boolean;
            campos: number;
            reglas: number;
            estado: string;
            filas: number | null;
            bloqueantes: number;
            advertencias: number;
        };
        Avance: {
            cargados: number;
            total: number;
        };
        Inicio: {
            periodos: components["schemas"]["Periodo"][];
            periodo: components["schemas"]["Periodo"] | null;
            jurisdiccion: string | null;
            jurisdicciones: string[];
            presentacion: components["schemas"]["Presentacion"] | null;
            archivos: components["schemas"]["ArchivoDelPeriodo"][];
            avance: components["schemas"]["Avance"];
        };
        Periodo: {
            codigo: string;
            estado: string;
            /** Format: date */
            fecha_desde: string;
            /** Format: date */
            fecha_hasta: string;
        };
        Permisos: {
            cargar: boolean;
            presentar: boolean;
            editar_datos: boolean;
            revisar: boolean;
            administrar: boolean;
        };
        Presentacion: {
            id: number;
            estado: string;
            estado_legible: string;
        };
        Seccion: {
            clave: string;
            etiqueta: string;
            detalle: string;
            ruta: string;
            en_v2: boolean;
        };
        Sesion: {
            instancia: string;
            usuario: string;
            rol: string | null;
            nombre_del_rol: string;
            es_nacional: boolean;
            jurisdiccion: string | null;
            permisos: components["schemas"]["Permisos"];
            menu: components["schemas"]["Seccion"][];
            csrf_token: string;
            salir: string;
            aviso: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    mir_inicio_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Inicio"];
                };
            };
        };
    };
    mir_sesion_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sesion"];
                };
            };
        };
    };
}
